name: Publish to npm

on:
  push:
    tags:
      - "v*.*.*" # 触发规则：以 v 开头的标签
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug NODE_AUTH_TOKEN
        run: echo "NODE_AUTH_TOKEN is ${{ secrets.NPM_TOKEN }}"

      - name: 安装 node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"

      - name: Install pnpm
        run: |
          npm install -g pnpm@10.*

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build project
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}